import React from 'react';
import { Link } from 'react-router-dom';
import { SparklesIcon, GlobeAltIcon, StarIcon, MapIcon } from '@heroicons/react/24/outline';

export default function PublicHomePage() { // Renamed component
  return (
    <div className="min-h-screen bg-white text-gray-800">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-blue-600 to-indigo-700 text-white py-24 md:py-32 overflow-hidden shadow-lg">
        <div className="absolute inset-0 z-0 opacity-10">
          <svg className="w-full h-full" fill="none" viewBox="0 0 1000 1000" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <linearGradient id="gradient1" x1="0%" y1="0%" x2="100%" y2="100%">
                <stop offset="0%" stopColor="rgba(255, 255, 255, 0.1)"></stop>
                <stop offset="100%" stopColor="rgba(255, 255, 255, 0.05)"></stop>
              </linearGradient>
            </defs>
            <circle cx="200" cy="200" r="150" fill="url(#gradient1)"></circle>
            <circle cx="800" cy="500" r="100" fill="url(#gradient1)"></circle>
            <circle cx="500" cy="800" r="200" fill="url(#gradient1)"></circle>
            <rect x="50" y="50" width="100" height="100" fill="url(#gradient1)"></rect>
          </svg>
        </div>

        <div className="max-w-screen-xl mx-auto px-6 relative z-10 text-center">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight mb-6">
            Your Next <span className="text-pink-300">Adventure</span> Awaits!
          </h1>
          <p className="text-lg sm:text-xl text-blue-100 mb-10 max-w-2xl mx-auto">
            Plan, explore, and cherish your dream trips. From bustling cities to serene landscapes, we help you make every journey unforgettable.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Link
              to="/login" // Redirect to login for unauthenticated users
              className="bg-pink-500 hover:bg-pink-600 text-white font-semibold py-3 px-8 rounded-full shadow-lg transform hover:scale-105 transition-all duration-300 flex items-center justify-center"
            >
              <StarIcon className="h-5 w-5 mr-2" /> Start Your Bucket List
            </Link>
            <Link
              to="/login" // Redirect to login for unauthenticated users
              className="bg-white text-blue-700 hover:bg-blue-50 hover:text-blue-800 font-semibold py-3 px-8 rounded-full shadow-md transform hover:scale-105 transition-all duration-300 flex items-center justify-center"
            >
              <GlobeAltIcon className="h-5 w-5 mr-2" /> Explore Destinations
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-white">
        <div className="max-w-screen-xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-12">How DreamTrip Helps You Travel Smarter</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            <div className="bg-gray-50 p-8 rounded-lg shadow-md hover:shadow-xl transition-shadow duration-300">
              <StarIcon className="h-10 w-10 text-pink-500 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Build Your Dream List</h3>
              <p className="text-gray-600">
                Easily add all your must-visit places and travel aspirations to your personalized bucket list.
              </p>
            </div>
            <div className="bg-gray-50 p-8 rounded-lg shadow-md hover:shadow-xl transition-shadow duration-300">
              <SparklesIcon className="h-10 w-10 text-blue-500 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-3">AI-Powered Itineraries</h3>
              <p className="text-gray-600">
                Get smart, customized travel plans generated by AI, tailored to your preferences.
              </p>
            </div>
            <div className="bg-gray-50 p-8 rounded-lg shadow-md hover:shadow-xl transition-shadow duration-300">
              <MapIcon className="h-10 w-10 text-green-500 mx-auto mb-4" />
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Explore & Discover</h3>
              <p className="text-gray-600">
                Find inspiration, hidden gems, and popular attractions for your next adventure.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Call to Action Section */}
      <section className="bg-blue-50 py-16">
        <div className="max-w-screen-xl mx-auto px-6 text-center">
          <h2 className="text-3xl font-bold text-blue-900 mb-6">Ready to Start Planning?</h2>
          <p className="text-blue-700 text-lg mb-8 max-w-xl mx-auto">
            Join thousands of travelers making their dream trips a reality with DreamTrip.
          </p>
          <Link
            to="/register" // Changed to register for new users
            className="bg-pink-600 hover:bg-pink-700 text-white font-bold py-3 px-10 rounded-full text-lg shadow-xl transform hover:scale-105 transition-all duration-300"
          >
            Get Started Now
          </Link>
        </div>
      </section>
    </div>
  );
}